### ISSUE TITLE
loading-spinner

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#16]
## Value statement - a requirement, not a solution
As a **User** 
I need **an indicator that something is loading** 
so that **i am reassured the page is working** 

## Acceptance criteria
- [x] a loading spinner to bridge loading times on initial loading of the page.

## Tasks
- [x] research how to write a loading-spinner as a single component.
- [x] implement Loadingspinner.
- [x] resarch testing of the loading Spinner
- [x] test the Component

## Size
(large)
