### ISSUE TITLE
Improve Loadingspinner

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#19]
## Value statement - a requirement, not a solution
As a **user** 
**the loadingspinner should display sharply**
so that **its easy on the eye**

## Acceptance criteria
- [x] Sharply displayed loading-animation on every display size.

## Tasks
- [ ] Research better loading-spinner alternatives on NPM
- [x] Research alternatives to a giv. (Are there animated svg's?)

## Size
medium
