### ISSUE TITLE
Create Listcomponent

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#3]
## Value statement - a requirement, not a solution
As a **Player** 
I benefit from **additional Information displayed in the List**
to **get an correct idea of that monster** quicker.

## Description (Text, Scribble, Wireframe, Design)
<img width="291" alt="Bildschirmfoto 2020-08-31 um 06 43 52" src="https://user-images.githubusercontent.com/67914612/91683928-3f4dce80-eb56-11ea-9474-f63fae1c4b17.png">

## Acceptance criteria
- [x] Display the name, type and challenge-rating of every monster in the component of the list

## Tasks
- [x] Define a design of a list-component in Storybook.
- [x] Build a component with interchangeable text for monstername, type and challenge-rating.
- [x] Fetch the additional information to every monster.
- [x] Insert the additional information from the fetch in the component
- [x] Write  a Unittest

## Size
(large)
