### ISSUE TITLE
Onboarding-Screen with Fetch-Progress-Indicator

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#32]
## Value statement - a requirement, not a solution
As a **user** 
I need **an indicator for the fetch-progress** 
so that **i am reassured the page is still loading, and didn't stop** 

## Acceptance criteria
- [ ] The progress of the fetch gets monitored ...
- [ ] ... and gets displayed in an animation.

## Tasks
- [ ] Write a custom-hook for the fetch-mechanic
- [ ] research progress animation

## Size
(large)
