### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#34]
## Value statement - a requirement, not a solution
As a **Player** 
I need **to save and my favourite monsters ** 
so that **i can find them qickly again** 

## Description (Text, Scribble, Wireframe, Design)

<img width="846" alt="Bildschirmfoto 2020-09-29 um 12 11 49" src="https://user-images.githubusercontent.com/67914612/94545572-fec49c00-024c-11eb-94c6-598bcf54db0a.png">

A Favourite-Button in every monster-item in the list on the landingpage to mark that monster as a favourite. Additionaly a button in the header which, when clicked, shows only the favourites

## Acceptance criteria
- [ ] Favourite-Toggle-Button in every monsteritem.
- [ ] Favourite category in the header, which, when clicked, shows only the favourites on the Landingpage.
- [ ] The existing FuzzySearch works on the Favourites as well.

## Tasks
- [ ] Function to toggle property "favourite: true/false," on every Monsteritem im monsterdetails-array
- [ ] Add favourite Button to OneMonster.js to call toggleFavourite function.
- [ ] Load Favourites in a State and Integrate in AllMonsters before the call of FuzzySearch.
- [ ] Add button to toggle between giving Favourites and all Monsters to give into the FuzzySearch.
- [ ] Unit-test for the Buttons
- [ ] Integration test for favourite-Function.

## Size
(large)
