### ISSUE TITLE
Fetch Monsterlist

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#4]
## Value statement - a requirement, not a solution
As a **Player** 
I need **the Monsterlist** 
to **gather the scope of the information provided** 

## Description (Text, Scribble, Wireframe, Design)

![Wireframe Userstory1](https://user-images.githubusercontent.com/67914612/91539464-a763a100-e919-11ea-8913-f17dad3f2c9a.png)

## Acceptance criteria

- [x] Display the full list of Monsters 

## Tasks
- [x] Semantically indicative Headline
- [x] Fetch the Api-List
- [x] Show the List on the target-element (unformatted)
- [x] Write Tests with jest
- [x] Fetch List

## Size
(large)
