### ISSUE TITLE
Create-Detailpage-Component

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#5]
## Value statement - a requirement, not a solution
As a **player** 
I need **a clear display of each monster** 
to use **in my dnd-preparation and game**.

## Acceptance criteria
- [x] Display Some indicative Information of the Monster. (Name, Type, CR, Stats)
- [x] Every Monsters Detailpage is reachable with their name as route.

## Tasks
- [x] Create a detailpage as Component (Not all Information required yet)
- [x] Install router.
- [x] determine route-names.
- [x] Write Component-Test.
- [x] Implement in Storybook.

## Size
(large)
