### ISSUE TITLE
PDF-Export detailpage

### ISSUE THREAD

**Issue by janhenrikfock** [janhenrikfock/monsters-of-dnd#8]
## Value statement - a requirement, not a solution
As a **player** 
I need **to extract the data from the app ** 
to be able to **modify the data for the preparation.**

## Acceptance criteria
- [x] The full data from the detailpage extractable via pdf-export.

## Tasks
- [x] Research the PDF-Export 
- [x] Implement PDF-Export

## Size
(large)
